name: comic_segmentation
description: "Flutter application for AI-powered comic page segmentation."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartantic_ai: ^1.3.0
  image_picker: ^1.2.1
  flutter_riverpod: ^3.0.3
  google_fonts: ^6.3.2
  dartantic_interface: ^1.1.0
  json_schema: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  dartantic_interface: 1.1.0
